# Generated by Django 2.2.5 on 2019-10-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDetail',
            fields=[
                ('movieName', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('synopsis', models.TextField(max_length=200)),
                ('avgRating', models.IntegerField(max_length=15)),
            ],
            options={
                'db_table': 'movieDetail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('movieName', models.CharField(max_length=30)),
                ('review', models.TextField(max_length=200)),
                ('rating', models.IntegerField(max_length=15)),
            ],
            options={
                'db_table': 'userReview',
                'managed': False,
            },
        ),
    ]
