# Generated by Django 2.2.5 on 2019-10-01 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_moviedetail_userreview'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='moviedetail',
            table='moviedetail',
        ),
        migrations.AlterModelTable(
            name='userreview',
            table='userreview',
        ),
    ]
